/**
 * Cloudfiles Setup Script v1.0.0
 * 
 * This script will:
 * - Login to Cloudflare
 * - Create Pages projects (or use existing)
 * - Get actual production URL from deployment output
 * - Update config.js
 * - Deploy initial main.json (only for NEW projects)
 * 
 * IMPORTANT WARNINGS:
 * - This project uses Cloudflare Pages for storage (free tier)
 * - Use a secondary Cloudflare account (NOT your main account)
 * - Do NOT store important files without backup
 * 
 * Prerequisites:
 * - Node.js >= 18.0.0
 * - Wrangler CLI (will be auto-installed)
 * - Cloudflare account (free tier works)
 */

import { execa } from 'execa';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import readline from 'readline';

// Get current script directory
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = __dirname;

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function runCommand(command, args) {
  console.log(`\n▶ Running: ${command} ${args.join(' ')}`);
  const childProc = execa(command, args, { stdio: 'inherit' });
  await childProc;
}

async function runCommandCapture(command, args) {
  try {
    const { stdout, stderr } = await execa(command, args, { reject: false });
    return { stdout, stderr, success: true };
  } catch (error) {
    return { stdout: '', stderr: error.message, success: false };
  }
}

// Run command and capture output (for getting deployment URL)
async function runCommandCaptureOutput(command, args) {
  try {
    const { stdout } = await execa(command, args, { stdio: 'pipe' });
    return stdout;
  } catch (error) {
    return '';
  }
}

function updateConfig(mainProject, dataProject, mainUrl) {
  const configPath = path.join(PROJECT_ROOT, 'lib', 'config.js');
  
  const configContent = `// lib/config.js
// Description: Global configuration constants
// 
// This file is auto-generated by setup.js
// Do NOT edit manually unless you know what you're doing
//
// Run 'login.bat' to configure your project

import os from 'os';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '..');

// ========================================
// User Configuration (Auto-generated)
// ========================================

// [CUSTOMIZE] Main project name (Cloudflare Pages project name)
export const MAIN_PROJECT_NAME = '${mainProject}';

// [CUSTOMIZE] Data project name (for storing file data)
export const DATA_PROJECT_NAME = '${dataProject}';

// [CUSTOMIZE] Main project URL (Cloudflare Pages domain)
export const MAIN_PROJECT_URL = '${mainUrl}';

// ========================================
// System Configuration (Do NOT modify)
// ========================================

export const UPDATE_DIR = path.join(PROJECT_ROOT, 'update');
export const DOWNLOAD_DIR = path.join(PROJECT_ROOT, 'download');
export const CHUNK_DIR = path.join(PROJECT_ROOT, 'chunks');
export const PREVIEW_CACHE_DIR = path.join(PROJECT_ROOT, 'preview_cache');
export const CHUNK_SIZE = 25 * 1024 * 1024;
export const TEMP_SITE_DIR = path.join(PROJECT_ROOT, 'temp-cloudfiles-site');
export const TEMP_CHUNK_DIR = path.join(PROJECT_ROOT, 'temp-chunk-upload');
export const MAX_RETRIES = 5;

export const MAX_WORKERS = Math.max(1, Math.min(8, Math.floor(os.cpus().length / 2) || 1));
export const DISTRIBUTED_ARCHITECTURE = false;
`;

  fs.writeFileSync(configPath, configContent, 'utf8');
  console.log('✓ config.js updated successfully');
}

async function checkLogin() {
  const result = await runCommandCapture('wrangler', ['whoami']);
  
  if (result.stdout.includes('@') || result.stdout.includes('Account')) {
    return true;
  }
  
  if (result.stderr.includes('not authenticated') || result.stdout.includes('not authenticated')) {
    return false;
  }
  
  return result.success;
}

async function getExistingProjects() {
  const result = await runCommandCapture('wrangler', ['pages', 'project', 'list']);
  
  const projects = [];
  
  if (result.stdout) {
    const lines = result.stdout.split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      
      if (!trimmed) continue;
      if (trimmed.includes('────')) continue;
      if (trimmed.includes('┌') || trimmed.includes('├') || trimmed.includes('└')) continue;
      if (trimmed.includes('│')) {
        const parts = trimmed.split('│').map(p => p.trim()).filter(p => p);
        if (parts.length > 0) {
          const name = parts[0];
          if (name && name !== 'name' && !name.includes('─') && name.length > 0) {
            projects.push(name);
          }
        }
      } else {
        const parts = trimmed.split(/\s+/);
        if (parts.length > 0 && parts[0] && !parts[0].includes('─') && !parts[0].includes('Getting')) {
          const name = parts[0];
          if (name.length > 0 && name.length < 100 && !name.startsWith('⛅')) {
            projects.push(name);
          }
        }
      }
    }
  }
  
  return projects;
}

// Extract production URL from preview URL
// Preview:  https://RANDOM_HASH.project-name.pages.dev
// Production: https://project-name.pages.dev
function extractProductionUrl(previewUrl) {
  try {
    const url = new URL(previewUrl);
    const hostname = url.hostname;
    
    // Format: randomhash.projectname-suffix.pages.dev
    const parts = hostname.split('.');
    
    if (parts.length >= 4 && parts[0].match(/^[a-f0-9]{8,}$/i)) {
      // First part is a random hash, remove it
      parts.shift();
      const productionHost = parts.join('.');
      return `https://${productionHost}`;
    }
    
    // Already a production URL
    return previewUrl;
  } catch (e) {
    return previewUrl;
  }
}

async function getProjectUrlFromDeployment(projectName) {
  console.log(`Getting production URL for project: ${projectName}`);
  
  // Create a minimal temp file to deploy
  const tempDir = path.join(PROJECT_ROOT, 'temp-url-check');
  if (!fs.existsSync(tempDir)) {
    fs.mkdirSync(tempDir, { recursive: true });
  }
  
  // Create a dummy file
  fs.writeFileSync(path.join(tempDir, '.keep'), '');
  
  try {
    // Deploy and capture output
    const output = await runCommandCaptureOutput('wrangler', [
      'pages', 'deploy', tempDir,
      '--project-name', projectName,
      '--branch', 'main'
    ]);
    
    // Look for deployment URL in output
    const urlMatch = output.match(/https:\/\/[^\s]+\.pages\.dev/);
    
    if (urlMatch) {
      const previewUrl = urlMatch[0];
      console.log(`Preview URL: ${previewUrl}`);
      
      const productionUrl = extractProductionUrl(previewUrl);
      console.log(`Production URL: ${productionUrl}`);
      
      return productionUrl;
    }
  } catch (error) {
    console.log(`Could not get URL from deployment: ${error.message}`);
  } finally {
    // Cleanup
    try {
      fs.rmSync(tempDir, { recursive: true, force: true });
    } catch (e) {}
  }
  
  // Fallback
  return `https://${projectName}.pages.dev`;
}

// Check if main.json exists on the project
async function checkMainJsonExists(mainUrl) {
  try {
    const response = await fetch(`${mainUrl}/main.json`, { method: 'HEAD' });
    return response.ok;
  } catch (error) {
    return false;
  }
}

// Deploy initial main.json (only for new projects)
async function deployInitialMainJson(mainProject) {
  console.log('Deploying initial main.json...\n');
  
  // Create temp directory
  const tempDir = path.join(PROJECT_ROOT, 'temp-deploy');
  if (!fs.existsSync(tempDir)) {
    fs.mkdirSync(tempDir, { recursive: true });
  }
  
  // Create empty main.json
  const mainJson = {
    fs_root: {
      type: 'folder',
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      children: {}
    }
  };
  
  const mainJsonPath = path.join(tempDir, 'main.json');
  fs.writeFileSync(mainJsonPath, JSON.stringify(mainJson, null, 2), 'utf8');
  
  try {
    // Deploy using wrangler
    await runCommand('wrangler', ['pages', 'deploy', tempDir, '--project-name', mainProject, '--branch', 'main']);
    console.log('\n✓ main.json deployed successfully!\n');
  } catch (error) {
    console.log(`\n! Could not deploy main.json: ${error.message}\n`);
  } finally {
    // Cleanup
    try {
      fs.rmSync(tempDir, { recursive: true, force: true });
    } catch (e) {}
  }
}

async function main() {
  console.log('\n========================================');
  console.log('  Cloudfiles Setup v1.0.0');
  console.log('========================================\n');

  // Step 1: Login
  console.log('[Step 1/4] Checking login status...\n');
  
  const isLoggedIn = await checkLogin();
  
  if (isLoggedIn) {
    console.log('✓ Already logged in!\n');
    const result = await runCommandCapture('wrangler', ['whoami']);
    if (result.stdout) {
      console.log(result.stdout);
    }
  } else {
    console.log('Not logged in. Starting login flow...\n');
    await runCommand('wrangler', ['login']);
    console.log('\n✓ Login successful!\n');
  }

  // Step 2: Get project list
  console.log('\n[Step 2/4] Fetching existing projects...\n');
  
  const existingProjects = await getExistingProjects();
  
  if (existingProjects.length > 0) {
    console.log(`Found ${existingProjects.length} existing projects:`);
    existingProjects.forEach(p => console.log(`  - ${p}`));
    console.log('');
  } else {
    console.log('No existing projects found.\n');
  }

  // Step 3: Get project name
  console.log('[Step 3/4] Configure project\n');
  
  const projectName = await question('Enter your project name (e.g., my-cloudfiles): ');
  
  if (!projectName || projectName.trim() === '') {
    console.log('\n✗ Project name is required!');
    rl.close();
    process.exit(1);
  }

  const mainProject = projectName.trim();
  const dataProject = `${mainProject}-data`;

  // Check if projects already exist
  const mainExists = existingProjects.includes(mainProject);
  const dataExists = existingProjects.includes(dataProject);
  const isNewProject = !mainExists;

  console.log(`\nProject configuration:`);
  console.log(`  Main project: ${mainProject} ${mainExists ? '(EXISTS)' : '(NEW)'}`);
  console.log(`  Data project: ${dataProject} ${dataExists ? '(EXISTS)' : '(NEW)'}`);
  
  if (isNewProject) {
    console.log('\n  ℹ️  New project detected. Will create projects and deploy initial files.');
  } else {
    console.log('\n  ℹ️  Existing project detected. Will only update local config (no data loss).');
  }
  console.log('');

  const confirm = await question('Continue? (Y/N): ');
  if (confirm.toUpperCase() !== 'Y') {
    console.log('\nCancelled.');
    rl.close();
    process.exit(0);
  }

  // Step 4: Create projects if needed (only for new projects)
  console.log('\n[Step 4/4] Setting up...\n');

  if (isNewProject) {
    // Create main project
    console.log(`Creating main project "${mainProject}"...`);
    try {
      await runCommand('wrangler', ['pages', 'project', 'create', mainProject, '--production-branch=main']);
      console.log(`\n✓ Main project "${mainProject}" created!\n`);
    } catch (error) {
      const errorMsg = error.message || '';
      if (errorMsg.includes('already exists')) {
        console.log(`\n✓ Main project "${mainProject}" already exists.\n`);
      } else {
        console.log(`\n! Could not create main project: ${errorMsg}\n`);
      }
    }

    // Create data project
    console.log(`Creating data project "${dataProject}"...`);
    try {
      await runCommand('wrangler', ['pages', 'project', 'create', dataProject, '--production-branch=main']);
      console.log(`\n✓ Data project "${dataProject}" created!\n`);
    } catch (error) {
      const errorMsg = error.message || '';
      if (errorMsg.includes('already exists')) {
        console.log(`\n✓ Data project "${dataProject}" already exists.\n`);
      } else {
        console.log(`\n! Could not create data project: ${errorMsg}\n`);
      }
    }
  } else {
    console.log(`✓ Using existing main project "${mainProject}"`);
    console.log(`✓ Using existing data project "${dataProject}"\n`);
  }

  // Get production URL
  console.log('Getting production URL...\n');
  const mainUrl = await getProjectUrlFromDeployment(mainProject);
  
  console.log(`\n✓ Production URL: ${mainUrl}\n`);
  
  // Update config.js
  try {
    const libPath = path.join(PROJECT_ROOT, 'lib');
    if (!fs.existsSync(libPath)) {
      fs.mkdirSync(libPath, { recursive: true });
    }
    
    updateConfig(mainProject, dataProject, mainUrl);
    console.log('');
  } catch (error) {
    console.log(`✗ Failed to update config.js: ${error.message}\n`);
  }

  // Only deploy main.json for NEW projects
  if (isNewProject) {
    console.log('Deploying initial main.json for new project...\n');
    await deployInitialMainJson(mainProject);
  } else {
    // Check if main.json exists for existing project
    const mainJsonExists = await checkMainJsonExists(mainUrl);
    
    if (!mainJsonExists) {
      console.log('⚠️  main.json not found on existing project, deploying...\n');
      await deployInitialMainJson(mainProject);
    } else {
      console.log('✓ main.json already exists, skipping deployment.\n');
      console.log('  Your existing files are safe!\n');
    }
  }

  // Done
  console.log('========================================');
  console.log('  Setup Complete!');
  console.log('========================================\n');
  console.log('Your configuration:');
  console.log(`  MAIN_PROJECT_NAME = '${mainProject}'`);
  console.log(`  DATA_PROJECT_NAME = '${dataProject}'`);
  console.log(`  MAIN_PROJECT_URL = '${mainUrl}'`);
  
  if (isNewProject) {
    console.log('\n✨ New project created successfully!');
  } else {
    console.log('\n✨ Configuration updated! Your existing files are preserved.');
  }
  
  console.log('\nNext steps:');
  console.log('  1. Run: start.bat');
  console.log('  2. Open: http://localhost:8000');
  console.log('  3. Or use CLI: node main.js up ./file.pdf /\n');

  rl.close();
}

main().catch((error) => {
  console.error('\nError:', error.message);
  rl.close();
  process.exit(1);
});
