// lib/config.js
// Description: Global configuration constants
// 
// This file is auto-generated by setup.js
// Do NOT edit manually unless you know what you're doing
//
// Run 'login.bat' to configure your project

import os from 'os';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '..');

// ========================================
// User Configuration (Auto-generated)
// ========================================

// [CUSTOMIZE] Cloudflare API Token (需要 Pages 编辑权限)
// 获取方式: https://dash.cloudflare.com/profile/api-tokens
export const CLOUDFLARE_API_TOKEN = 'your-api-token';

// [CUSTOMIZE] Cloudflare Account ID (可选，留空则自动检测)
// 获取方式: https://dash.cloudflare.com → 右侧 API 区域
export const CLOUDFLARE_ACCOUNT_ID = '';

// [CUSTOMIZE] Main project name (Cloudflare Pages project name)
export const MAIN_PROJECT_NAME = 'your-project-name';

// [CUSTOMIZE] Data project name (for storing file data)
export const DATA_PROJECT_NAME = 'your-project-name-data';

// [CUSTOMIZE] Main project URL (Cloudflare Pages domain)
export const MAIN_PROJECT_URL = 'https://your-project-name.pages.dev';

// ========================================
// System Configuration (Do NOT modify)
// ========================================

export const UPDATE_DIR = path.join(PROJECT_ROOT, 'update');
export const DOWNLOAD_DIR = path.join(PROJECT_ROOT, 'download');
export const CHUNK_DIR = path.join(PROJECT_ROOT, 'chunks');
export const PREVIEW_CACHE_DIR = path.join(PROJECT_ROOT, 'preview_cache');
export const CHUNK_SIZE = 25 * 1024 * 1024;
export const TEMP_SITE_DIR = path.join(PROJECT_ROOT, 'temp-cloudfiles-site');
export const TEMP_CHUNK_DIR = path.join(PROJECT_ROOT, 'temp-chunk-upload');
export const MAX_RETRIES = 5;

export const MAX_WORKERS = Math.max(1, Math.min(8, Math.floor(os.cpus().length / 2) || 1));
export const DISTRIBUTED_ARCHITECTURE = false;
